### PR TITLE
Delete forecasting.wiki zone

### PR DESCRIPTION
**Pull request by Universal-Omega**
They don't seem to be using our DNS anymore.
https://www.nslookup.io/domains/forecasting.wiki/dns-records

### CODE REVIEW

**Comment by dmehus** [comment]
@Universal-Omega The IPs linked at https://www.nslookup.io/domains/forecasting.wiki/dns-records trace back to `cp31.miraheze.org`, so it seems they're just preferring to use an `A` record rather than a `CNAME` record

**Comment by MacFan4000** [comment]
for reference, my conversation with them can be viewed at https://forecasting.wiki/wiki/User_talk:Nikos

**Comment by RhinosF1** [comment]
It looks like they've updated the proxy records so it now uses mw-lb with cloudflare dns

**Comment by dmehus** [comment]
> If you look at the SSL certificate, you can see the Intermediate certificate is not the typical LE one used for MH certs. It is using an alt that you can only use if you request access from LE. This would tell me that the site is proxied through a CDN (in this case CoudFlare).

Ah, okay, I see they're using CloudFlare nameservers, which in itself isn't a problem, but the CloudFlare certificate is how you tell they have CloudFlare proxying enabled.

I thought you had issues with them using our servers' IP addresses as A records rather than `mw-lb.miraheze.org` as a CNAME record, as I have definitely confirmed with Southparkfan that is okay to do as some DNS hosts don't allow CNAME records for the root domain.

**Comment by RhinosF1** [comment]
We don't need the dns zone as they aren't using our dns

**Comment by dmehus** [comment]
> We don't need the dns zone as they aren't using our dns

Yep, exactly.

**Comment by RhinosF1** [comment]
> I thought you had issues with them using our servers' IP addresses as A records rather than mw-lb.miraheze.org as a CNAME record, as I have definitely confirmed with Southparkfan that is okay to do as some DNS hosts don't allow CNAME records for the root domain.
We prefer CNAME and it will warn for most providers but cloudflare is one of 2 that it ignores this for and allows A records.

**Comment by RhinosF1** [comment]
> > > I thought you had issues with them using our servers' IP addresses as A records rather than mw-lb.miraheze.org as a CNAME record, as I have definitely confirmed with Southparkfan that is okay to do as some DNS hosts don't allow CNAME records for the root domain.
> > 
> > 
> > We prefer CNAME and it will warn for most providers but cloudflare is one of 2 that it ignores this for and allows A records.
> 
> Oh? Do they? I guess that's right. I hadn't checked. Maybe I was thinking of Gandi.net (whom I won't use for domain registrations anymore because they don't allow credit card auto-renewals, only account auto-top-ups).

Gandi are not on that list. It's Cloudflare & Dreamhost per https://github.com/miraheze/puppet/blob/master/modules/monitoring/files/check_reverse_dns.py#L77

**Comment by dmehus** [comment]
> > > > I thought you had issues with them using our servers' IP addresses as A records rather than mw-lb.miraheze.org as a CNAME record, as I have definitely confirmed with Southparkfan that is okay to do as some DNS hosts don't allow CNAME records for the root domain.
> > > 
> > > 
> > > We prefer CNAME and it will warn for most providers but cloudflare is one of 2 that it ignores this for and allows A records.
> > 
> > 
> > Oh? Do they? I guess that's right. I hadn't checked. Maybe I was thinking of Gandi.net (whom I won't use for domain registrations anymore because they don't allow credit card auto-renewals, only account auto-top-ups).
> 
> Gandi are not on that list. It's Cloudflare & Dreamhost per https://github.com/miraheze/puppet/blob/master/modules/monitoring/files/check_reverse_dns.py#L77

To be clear, I was agreeing with you and saying maybe I was thinking it was Gandi that did _not_ allow CNAMEs on the root domain. You said Cloudflare _does_.

**Review by dmehus — COMMENTED** [review]
Can we merge this then?

**Comment by Universal-Omega** [comment]
> Can we merge this then?

Probably, I just wanted to wait at first which is why I made it a draft for awhile, just if they wanted to switch back to our DNS, which they talked about for a minute. I don't know if they plan to or not.

**Pull request merged**
