### PR TITLE
create a "fake" entry for ns3

### PR DESCRIPTION
**Pull request by Pix1234**

### CODE REVIEW

**Comment by JohnFLewis** [comment]
ns1 is preferred as that’s the “authoritative” one. Having a secondary listen to a secondary is generally not recommended

**Comment by Southparkfan** [comment]
Is this ready to be merged?

**Comment by Pix1234** [comment]
I dont see why not

**Comment by dmehus** [comment]
LGTM. What's the idea behind creating a duplicate of ns2 in ns3?

**Comment by Southparkfan** [comment]
> LGTM. What's the idea behind creating a duplicate of ns2 in ns3?

In the past, there was an ns3 as well. While that server was taken out of service almost 4.5 years ago, there are still various custom domains using ns3.miraheze.org as a nameserver. Resolvers like 8.8.8.8 (Google) try to query an ns3 for records, but fail to do so (since ns3 didn't point to anything). On Miraheze servers, where Google's resolver is used for querying, Icinga checks occasionally failed because timeouts were hit for queries to 8.8.4.4 or 8.8.8.8.

**Comment by dmehus** [comment]
@Southparkfan Ah, thanks for the more detailed explanation (and to @Pix1234) for the explanation on IRC/Discord as well. Yeah, that makes sense, and there's probably no _easy_ way to tell how many clients are still using _ns3_ (so we could have them update), eh?

**Pull request merged**
