### PR TITLE
mh.org: add mwtask CNAME to active task

### PR DESCRIPTION
**Pull request by RhinosF1**
For ease of docs and stuff, same as for deployment.

### CODE REVIEW

**Review by dmehus — APPROVED** [review]
LGTM. :+1:

**Comment by JohnFLewis** [comment]
Would you round robin if multiple task servers existed?

**Comment by dmehus** [comment]
> Would you round robin if multiple task servers existed?
Ah, good point, for future planning when we have multiple mwtask servers.

**Comment by RhinosF1** [comment]
> Would you round robin if multiple task servers existed?

I can't imagine us ever doing this unless it was a multi-DC environment as task is supposed to be resourced to handle all maintenance operations. If it was multi-DC, you'd use the RW DC. If we did, a load balancer would work for this purpose.

**Pull request merged**
